name: Test
on: [ push ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@517a3b1b36b6f5727d97c46b7641767c1564b333 # pin@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rspec spec
